version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    labels:
      - dependencies
    schedule:
      interval: daily
    ignore:
      - dependency-name: org.junit.jupiter:junit-jupiter
        update-types:
          - version-update:semver-major # java 17 is required for junit-jupiter:6.+
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
    schedule:
      interval: daily