variables:
  APP_NAME: "read-csv"
  INSPECTION_ENABLED: 'false'
  TEST_ENABLED: 'false'
  ARTIFACTORY_PUBLISH: 'false'
  
include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-java.yml'
